#!/usr/bin/with-contenv bash

echo "Starting bot."

if [ $EFB_VERBOSE ]; then
    exec s6-setuidgid abc ehforwarderbot --profile ComWeChat -v
else
    exec s6-setuidgid abc ehforwarderbot --profile ComWeChat
fi
